modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/Mrbysco/EvasiveItems/issues"
license="MIT"

[[mods]]
modId="evasiveitems"
version="${file.jarVersion}"
displayName="Evasive Items"
displayURL="https://www.curseforge.com/minecraft/mc-mods/evasive-items"
authors="Mrbysco"
description='''
Keep your eyes off the prize in this unique take on item collection.
'''
credits="TelepathicGrunt for the idea"
[[dependencies.evasiveitems]]
modId="minecraft"
mandatory=true
versionRange="[1.19.3,1.20)"
ordering="NONE"
side="BOTH"